version: "3.10"

services:

  rabbitmq:
    image: rabbitmq:management
    command: rabbitmq-server
    tty: true
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis
    ports:
      - "6379:6379"

  server:
    container_name: server
    image: server
    build: ./src/server
    env_file:
      - ./src/server/.env
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - redis

  workers:
    container_name: workers
    image: workers
    build: ./src/workers
    env_file:
      - ./src/workers/.env
    depends_on:
      - rabbitmq
      - redis
